version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ecommerce2025
      POSTGRES_DB: ecommerce
    ports:
      - "5433:5432"
